[window]
startup_mode = "Maximized"
padding = { x = 14, y = 7 }
dynamic_padding = true
opacity = 1.0

[scrolling]
history = 100000  # Aumente o histórico para 100k linhas (ajuste conforme necessário)
multiplier = 3    # Velocidade do scroll

[mouse]
hide_when_typing = false  # Permite scroll mesmo digitando


[colors]
[colors.primary]
background = "#090f14"


[keyboard]
bindings = [
  { key = "F1", action = "ToggleViMode" },  # Alterna modo de seleção
  { key = "t", mods = "Control|Shift", command = { program = "tmux", args = ["new-window"] } },
  { key = "w", mods = "Control|Shift", command = { program = "tmux", args = ["kill-window"] } },

  # Navegação entre janelas
  { key = "Tab", mods = "Control", command = { program = "tmux", args = ["next-window"] } },
  { key = "Tab", mods = "Control|Shift", command = { program = "tmux", args = ["previous-window"] } },

  # Navegação entre painéis (←→↑↓)
  { key = "h", mods = "Control", command = { program = "tmux", args = ["select-pane", "-L"] } },
  { key = "l", mods = "Control", command = { program = "tmux", args = ["select-pane", "-R"] } },
  # ... (similar para Up/Down)
  { key = "k", mods = "Control", command = { program = "tmux", args = ["select-pane", "-U"] } },
  { key = "j", mods = "Control", command = { program = "tmux", args = ["select-pane", "-D"] } },

  { key = "w", mods = "Control|Super", command = { program = "tmux", args = ["kill-pane"] } },

  # Split vertical (Ctrl+Shift+H)
  { key = "H", mods = "Control|Alt", command = { program = "tmux", args = ["split-window", "-h"] } },

  # Split horizontal (Ctrl+Shift+V)
  { key = "V", mods = "Control|Alt", command = { program = "tmux", args = ["split-window", "-v"] } },
  # { key = "U", mods = "Alt", action = "ScrollLineUp" },
  # { key = "D", mods = "Alt", action = "ScrollLineDown" }

  { key = "H", mods = "Alt", command = { program = "tmux", args = ["resize-pane", "-L", "1"] } },
  { key = "L", mods = "Alt", command = { program = "tmux", args = ["resize-pane", "-R", "1"] } },
  { key = "K", mods = "Alt", command = { program = "tmux", args = ["resize-pane", "-U", "1"] } },
  { key = "J", mods = "Alt", command = { program = "tmux", args = ["resize-pane", "-D", "1"] } },


  { key = "R", mods = "Super|Shift", command = { program = "tmux", args = ["source-file", "~/.tmux.conf"] } },
]

[terminal]
shell = { program = "/run/current-system/sw/bin/bash", args = ["--login", "-c", "tmux attach -t main || tmux new -s main"] }

[selection]
save_to_clipboard = true  # Permite copiar mesmo com tmux
